BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Reservation] ALTER COLUMN [start_time] DATETIME2 NOT NULL;
ALTER TABLE [dbo].[Reservation] ALTER COLUMN [end_time] DATETIME2 NOT NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
